### ISSUE TITLE
Migrate plugin data

### ISSUE THREAD

**Issue by ThiefMaster** [indico/indico-migrate#11]
- [ ] Chat
- [ ] Invenio Importer - *just settings*
- [ ] LiveSync - *if we ignore it people need to add their agent manually and either run an initial export or set it as run via indico shell*
- [ ] PayPal Payment - **important event settings such as the recipient of the payment**
- [ ] Piwik - *just settings*
- [ ] Search Invenio - *just settings*
- [ ] VC Vidyo

**Comment by ThiefMaster** [comment]
Probably best to just add it to indico-migrate and add a `--plugin` option (`multiple=True`) where we can select which plugin data should be migrated.

Vidyo and LiveSync are probably the most tricky ones since they really need the plugin to be installed for the migration as they have their own database tables.

**Comment by maxfischer2781** [comment]
Not a strict requirement, but it would be nice if third party plugins could provide their own conversion plugin. For example, we use a custom ePayment plugin with its own transaction type in indico 1.2 and indico 2.0.

**Comment by ThiefMaster** [comment]
Since migration is a one-time thing it's better if you just clone the repo and add your own code. So far nobody needed plugin-related migrations and it'd take quite some development effort to add something nice/extensible here for little gain.

**Comment by ThiefMaster** [comment]
Closing this one since most people migrated by now and nobody asked for any of this plugin data to be migrated.
