### ISSUE TITLE
layout and type of events created by CDSAgenda not properly converted

### ISSUE THREAD

**Issue by jouvin** [indico/indico-migrate#13]
indico-migrate on our 1.2 db reported a non negligible number of layout problems with the following message (for example event `a0698` in our db):
```
layout      Skipping some settings, missing _styleMngr attribute
```

Looking in more details, it appeared that the events causing this problem are coming from CDSAgenda (said explicitly in management mode) and have the layout shown in the attached [screenshot](https://user-images.githubusercontent.com/1511937/28225957-9feadca4-68d4-11e7-97b5-7a0de3c51400.PNG) (the traditional CDSAgenda look if I remember properly). Their "default style" setting is 'CDSAgenda style'. Those events are created in v2 but as a conference rather than a meeting (despite the event type in 1.2 is `meeting`) and I didn't find how to change it. Also the timetable style is the default one rather than the "indico style" which is very close to the CDSAgenda one (only the background customization in the description is not done).

Even if nobody should use the CDSAgenda layout for a new event, for a migrated one the layout should be as close as possible (if not identical) to what it was in 1.2 (the description yellow background is among the details that can be ignored IMO).

**Comment by ThiefMaster** [comment]
the wrong types are a very good catch! we'll release a fixed version soon where the types of these events are correctly migrated.

**Comment by ThiefMaster** [comment]
I don't think we want to add a cdsagenda-like style to Indico, especially considering that there aren't any real drawbacks from these events using the default style now.

**Comment by jouvin** [comment]
@ThiefMaster I am not sure to understand... I never suggested readding a cdsagenda-like style but using the timetable so-called "Indico-style" for these events. Currently "default" is used and this is not the same one. My point was that Indico-style was closer.

**Comment by ThiefMaster** [comment]
oh, so just the normal meeting style - that's already the case with the event type fix :)
