### ISSUE TITLE
timetable errors

### ISSUE THREAD

**Issue by jouvin** [indico/indico-migrate#15]
I have also a number of events where indico-migrate reported a timetable error like:
```
timetable   Contribution <persistent broken MaKaC.conference.Contribution instance '\x00\x00\x00\x00\x00\x16\x8a#'> has no fields
```

An event with such an error in my database is `a0681`. I have no clue what the potential impact on the converted event could be.

I did a check to compare the occurence of this error with the layout error and I found that it is often but not always associated with a layout error. The attached [file](https://github.com/indico/indico-migrate/files/1149564/timetable.txt) is the result of the check done with the following command ($events containing all the event ids where a timetable error occured):
```
for event in $events; do echo Checking layout errors for $event; grep layout migration.log|grep " $event "; done>/tmp/timetable.list
```

From the visual checks I made, it seems to be again CDSAgenda events. And as usual you can look at these events in more details at http://indico.lal.in2p3.fr (v1.2).

**Comment by ThiefMaster** [comment]
Safe to ignore (maybe we should remove the warning, it's kind of useless): these contributions had no description and for some reason (probably that reason is called cdsagenda ;)) the object storing both custom fields and the description was missing too.

**Comment by jouvin** [comment]
Thanks.

**Comment by jouvin** [comment]
I let you close the issue!

**Comment by ThiefMaster** [comment]
i kept it open to remember removing the warning ;)
