### ISSUE TITLE
option to suppress garbage participant email

### ISSUE THREAD

**Issue by jouvin** [indico/indico-migrate#17]
In our 1.2 database, we have several invalid emails entered by participants who registered to events, in particular missing `@dom.ain`. Currently the migration script is adding `@example.com` which is not really making sense IMO. Could it be possible to have an option to delete such emails rather than modifying them (keeping the participants)?

**Comment by ThiefMaster** [comment]
All registrants/participants need to have an email address, so not using an email address at all is not a good option. Storing an empty address would technically work, but it would prevent us from ever adding e.g. a CHECK constraint that enforces a non-empty string in the column.

Using `@example.com` has the advantage of having a valid-looking email (so if someone were to edit such a registration it would not fail with a validation error) while still being obviously not a real email (example.com is an "official" example domain (RFC6761)).

**Comment by jouvin** [comment]
OK then! Checking a few events, I think that many old events have participants registered without an email... I guess it has been allowed at some point, at least in CDS Agenda! That means that you will have a hard time to put a constraint on this column in the DB that the value should not be empty...

**Comment by ThiefMaster** [comment]
We use `no-email[+n]@example.com` for these, so we don't have any empty emails. You can actually see all of these placeholder emails using this SQL query:

    SELECT first_name, last_name, email FROM event_registration.registrations WHERE email LIKE '%@example.com';

**Comment by jouvin** [comment]
You are right! Thanks.
