### ISSUE TITLE
'Alarm' object has no attribute 'startDateTime'

### ISSUE THREAD

**Issue by mokhinetc** [indico/indico-migrate#23]
Hi,

I am getting the following errors when doing an indico Migration:

```
Traceback (most recent call last): |/opt/indico/.venv/bin/indico-migrate:11 [<module>]
 |/opt/indico/.venv/local/lib/python2.7/site-packages/indico_migrate/cli.py:126 [main]
 |/opt/indico/.venv/local/lib/python2.7/site-packages/click/core.py:722 [__call__]
 |/opt/indico/.venv/local/lib/python2.7/site-packages/click/core.py:697 [main]
 |/opt/indico/.venv/local/lib/python2.7/site-packages/click/core.py:895 [invoke]
 |/opt/indico/.venv/local/lib/python2.7/site-packages/click/core.py:535 [invoke]
 |/opt/indico/.venv/local/lib/python2.7/site-packages/indico_migrate/cli.py:122 [cli]
 debug=debug, **kwargs)
 |/opt/indico/.venv/local/lib/python2.7/site-packages/indico_migrate/migrate.py:106 [migrate]
 |/opt/indico/.venv/local/lib/python2.7/site-packages/indico_migrate/importer.py:161 [run]
 |/opt/indico/.venv/local/lib/python2.7/site-packages/indico_migrate/util.py:323 [_f]
 |/opt/indico/.venv/local/lib/python2.7/site-packages/indico_migrate/steps/events/importer.py:183 [migrate]
 |/opt/indico/.venv/local/lib/python2.7/site-packages/indico_migrate/steps/events/importer.py:211 [migrate_event_data]
 |/opt/indico/.venv/local/lib/python2.7/site-packages/indico_migrate/steps/events/importer.py:137 [run_step]
 |/opt/indico/.venv/local/lib/python2.7/site-packages/indico_migrate/steps/events/__init__.py:83 [run]
 |/opt/indico/.venv/local/lib/python2.7/site-packages/indico_migrate/steps/events/misc.py:109 [migrate]
 if not alarm.startDateTime:
```

'Alarm' object has no attribute 'startDateTime'

**Comment by ThiefMaster** [comment]
From which version are you migrating?

**Comment by ThiefMaster** [comment]
Anyway, as a workaround you can replace [this line](https://github.com/indico/indico-migrate/blob/master/indico_migrate/steps/events/misc.py#L109) with this:

    if not getattr(alarm, 'startDateTime', None):

**Comment by mokhinetc** [comment]
@ThiefMaster 1.2 to 2.0

**Comment by mokhinetc** [comment]
@ThiefMaster under which file must I put the line of code??

**Comment by ThiefMaster** [comment]
`/opt/indico/.venv/local/lib/python2.7/site-packages/indico_migrate/steps/events/misc.py`

**Comment by mokhinetc** [comment]
Thanks, let me try that

**Comment by mokhinetc** [comment]
Hi Adrian,

I am now getting the following error:

Traceback (most recent call last): |/opt/indico/.venv/bin/indico-migrate:11
[<module>]
 |/opt/indico/.venv/local/lib/python2.7/site-packages/indico_migrate/cli.py:126
[main]
 |/opt/indico/.venv/local/lib/python2.7/site-packages/click/core.py:722
[__call__]
 |/opt/indico/.venv/local/lib/python2.7/site-packages/click/core.py:697
[main]
 |/opt/indico/.venv/local/lib/python2.7/site-packages/click/core.py:895
[invoke]
 |/opt/indico/.venv/local/lib/python2.7/site-packages/click/core.py:535
[invoke]
 |/opt/indico/.venv/local/lib/python2.7/site-packages/indico_migrate/cli.py:122
[cli]
 debug=debug, **kwargs)
 |/opt/indico/.venv/local/lib/python2.7/site-packages/indico_migrate/migrate.py:106
[migrate]
 |/opt/indico/.venv/local/lib/python2.7/site-packages/indico_migrate/importer.py:161
[run]
 |/opt/indico/.venv/local/lib/python2.7/site-packages/indico_migrate/util.py:323
[_f]
 |/opt/indico/.venv/local/lib/python2.7/site-packages/indico_migrate/steps/events/importer.py:183
[migrate]
 |/opt/indico/.venv/local/lib/python2.7/site-packages/indico_migrate/steps/events/importer.py:211
[migrate_event_data]
 |/opt/indico/.venv/local/lib/python2.7/site-packages/indico_migrate/steps/events/importer.py:137
[run_step]
 |/opt/indico/.venv/local/lib/python2.7/site-packages/indico_migrate/steps/events/__init__.py:83
[run]
 |/opt/indico/.venv/local/lib/python2.7/site-packages/indico_migrate/steps/events/papers.py:116
[migrate]
 |/opt/indico/.venv/local/lib/python2.7/site-packages/indico_migrate/steps/events/papers.py:344
[_migrate_papers]
 |/opt/indico/.venv/local/lib/python2.7/site-packages/indico_migrate/steps/events/papers.py:326
[_migrate_revisions]
 |/opt/indico/.venv/local/lib/python2.7/site-packages/sqlalchemy/orm/scoping.py:157
[do]
 |/opt/indico/.venv/local/lib/python2.7/site-packages/sqlalchemy/orm/session.py:2192
[flush]
 |/opt/indico/.venv/local/lib/python2.7/site-packages/sqlalchemy/orm/session.py:2312
[_flush]
 |/opt/indico/.venv/local/lib/python2.7/site-packages/sqlalchemy/util/langhelpers.py:66
[__exit__]
 |/opt/indico/.venv/local/lib/python2.7/site-packages/sqlalchemy/orm/session.py:2276
[_flush]
 |/opt/indico/.venv/local/lib/python2.7/site-packages/sqlalchemy/orm/unitofwork.py:389
[execute]
 |/opt/indico/.venv/local/lib/python2.7/site-packages/sqlalchemy/orm/unitofwork.py:548
[execute]
 |/opt/indico/.venv/local/lib/python2.7/site-packages/sqlalchemy/orm/persistence.py:181
[save_obj]
 |/opt/indico/.venv/local/lib/python2.7/site-packages/sqlalchemy/orm/persistence.py:835
[_emit_insert_statements]
 |/opt/indico/.venv/local/lib/python2.7/site-packages/sqlalchemy/engine/base.py:945
[execute]
 |/opt/indico/.venv/local/lib/python2.7/site-packages/sqlalchemy/sql/elements.py:263
[_execute_on_connection]
 |/opt/indico/.venv/local/lib/python2.7/site-packages/sqlalchemy/engine/base.py:1053
[_execute_clauseelement]
 |/opt/indico/.venv/local/lib/python2.7/site-packages/sqlalchemy/engine/base.py:1189
[_execute_context]
 |/opt/indico/.venv/local/lib/python2.7/site-packages/sqlalchemy/engine/base.py:1402
[_handle_dbapi_exception]
 |/opt/indico/.venv/local/lib/python2.7/site-packages/sqlalchemy/util/compat.py:203
[raise_from_cause]
 |/opt/indico/.venv/local/lib/python2.7/site-packages/sqlalchemy/engine/base.py:1182
[_execute_context]
 |/opt/indico/.venv/local/lib/python2.7/site-packages/sqlalchemy/engine/default.py:470
[do_execute]
 cursor.execute(statement, parameters)

(psycopg2.IntegrityError) null value in column "storage_backend" violates
not-null constraint
DETAIL:  Failing row contains (11, 688, 7, 0, null, application/pdf, ,
null, 341_D1_Middleton.pdf).
 [SQL: 'INSERT INTO event_paper_reviewing.files (contribution_id,
revision_id, size, storage_backend, content_type, md5, storage_file_id,
filename) VALUES (%(contribution_id)s, %(revision_id)s, %(size)s,
%(storage_backend)s, %(content_type)s, %(md5)s, %(storage_file_id)s,
%(filename)s) RETURNING event_paper_reviewing.files.id'] [parameters:
{'storage_file_id': None, 'filename': '341_D1_Middleton.pdf',
'contribution_id': 688, 'storage_backend': None, 'content_type':
'application/pdf', 'revision_id': 7, 'size': 0, 'md5': u''}]

**Comment by ThiefMaster** [comment]
Since you opened #24 to follow up the storage_backend error I'm closing this one.
