### ISSUE TITLE
(psycopg2.IntegrityError) null value in column "storage_backend" violates not-null constraint

### ISSUE THREAD

**Issue by mokhinetc** [indico/indico-migrate#24]
Good Morning,

I am getting the following error when trying to migrate fom 1.2 to 2.0.:

```
(psycopg2.IntegrityError) null value in column "storage_backend" violates not-null constraint
DETAIL:  Failing row contains (1, 109, 1, 0, null, application/pdf, , null, senekane_et_al_dp_student_t_mechanism.pdf).
 [SQL: 'INSERT INTO event_paper_reviewing.files (contribution_id, revision_id, size, storage_backend, content_type, md5, storage_file_id, filename) VALUES (%(contribution_id)s, %(revision_id)s, %(size)s, %(storage_backend)s, %(content_type)s, %(md5)s, %(storage_file_id)s, %(filename)s) RETURNING event_paper_reviewing.files.id'] [parameters: {'storage_file_id': None, 'filename': 'senekane_et_al_dp_student_t_mechanism.pdf', 'contribution_id': 109, 'storage_backend': None, 'content_type': 'application/pdf', 'revision_id': 1, 'md5': u'', 'size': 0}]
```

**Comment by ThiefMaster** [comment]
Hi, can you confirm this is the same problem as in the other issue? In any case, please include the traceback here.

**Comment by mokhinetc** [comment]
Yes it is the same issue.

**Comment by mokhinetc** [comment]
Traceback (most recent call last): |/opt/indico/.venv/bin/indico-migrate:11 [<module>]
 |/opt/indico/.venv/local/lib/python2.7/site-packages/indico_migrate/cli.py:126 [main]
 |/opt/indico/.venv/local/lib/python2.7/site-packages/click/core.py:722 [__call__]
 |/opt/indico/.venv/local/lib/python2.7/site-packages/click/core.py:697 [main]
 |/opt/indico/.venv/local/lib/python2.7/site-packages/click/core.py:895 [invoke]
 |/opt/indico/.venv/local/lib/python2.7/site-packages/click/core.py:535 [invoke]
 |/opt/indico/.venv/local/lib/python2.7/site-packages/indico_migrate/cli.py:122 [cli]
 debug=debug, **kwargs)
 |/opt/indico/.venv/local/lib/python2.7/site-packages/indico_migrate/migrate.py:106 [migrate]
 |/opt/indico/.venv/local/lib/python2.7/site-packages/indico_migrate/importer.py:161 [run]
 |/opt/indico/.venv/local/lib/python2.7/site-packages/indico_migrate/util.py:323 [_f]
 |/opt/indico/.venv/local/lib/python2.7/site-packages/indico_migrate/steps/events/importer.py:183 [migrate]
 |/opt/indico/.venv/local/lib/python2.7/site-packages/indico_migrate/steps/events/importer.py:211 [migrate_event_data]
 |/opt/indico/.venv/local/lib/python2.7/site-packages/indico_migrate/steps/events/importer.py:137 [run_step]
 |/opt/indico/.venv/local/lib/python2.7/site-packages/indico_migrate/steps/events/__init__.py:83 [run]
 |/opt/indico/.venv/local/lib/python2.7/site-packages/indico_migrate/steps/events/papers.py:116 [migrate]
 |/opt/indico/.venv/local/lib/python2.7/site-packages/indico_migrate/steps/events/papers.py:344 [_migrate_papers]
 |/opt/indico/.venv/local/lib/python2.7/site-packages/indico_migrate/steps/events/papers.py:326 [_migrate_revisions]
 |/opt/indico/.venv/local/lib/python2.7/site-packages/sqlalchemy/orm/scoping.py:157 [do]
 |/opt/indico/.venv/local/lib/python2.7/site-packages/sqlalchemy/orm/session.py:2192 [flush]
 |/opt/indico/.venv/local/lib/python2.7/site-packages/sqlalchemy/orm/session.py:2312 [_flush]
 |/opt/indico/.venv/local/lib/python2.7/site-packages/sqlalchemy/util/langhelpers.py:66 [__exit__]
 |/opt/indico/.venv/local/lib/python2.7/site-packages/sqlalchemy/orm/session.py:2276 [_flush]
 |/opt/indico/.venv/local/lib/python2.7/site-packages/sqlalchemy/orm/unitofwork.py:389 [execute]
 |/opt/indico/.venv/local/lib/python2.7/site-packages/sqlalchemy/orm/unitofwork.py:548 [execute]
 |/opt/indico/.venv/local/lib/python2.7/site-packages/sqlalchemy/orm/persistence.py:181 [save_obj]
 |/opt/indico/.venv/local/lib/python2.7/site-packages/sqlalchemy/orm/persistence.py:835 [_emit_insert_statements]
 |/opt/indico/.venv/local/lib/python2.7/site-packages/sqlalchemy/engine/base.py:945 [execute]
 |/opt/indico/.venv/local/lib/python2.7/site-packages/sqlalchemy/sql/elements.py:263 [_execute_on_connection]
 |/opt/indico/.venv/local/lib/python2.7/site-packages/sqlalchemy/engine/base.py:1053 [_execute_clauseelement]
 |/opt/indico/.venv/local/lib/python2.7/site-packages/sqlalchemy/engine/base.py:1189 [_execute_context]
 |/opt/indico/.venv/local/lib/python2.7/site-packages/sqlalchemy/engine/base.py:1402 [_handle_dbapi_exception]
 |/opt/indico/.venv/local/lib/python2.7/site-packages/sqlalchemy/util/compat.py:203 [raise_from_cause]
 |/opt/indico/.venv/local/lib/python2.7/site-packages/sqlalchemy/engine/base.py:1182 [_execute_context]
 |/opt/indico/.venv/local/lib/python2.7/site-packages/sqlalchemy/engine/default.py:470 [do_execute]
 cursor.execute(statement, parameters)

(psycopg2.IntegrityError) null value in column "storage_backend" violates not-null constraint
DETAIL:  Failing row contains (1, 109, 1, 0, null, application/pdf, , null, senekane_et_al_dp_student_t_mechanism.pdf).
 [SQL: 'INSERT INTO event_paper_reviewing.files (contribution_id, revision_id, size, storage_backend, content_type, md5, storage_file_id, filename) VALUES (%(contribution_id)s, %(revision_id)s, %(size)s, %(storage_backend)s, %(content_type)s, %(md5)s, %(storage_file_id)s, %(filename)s) RETURNING event_paper_reviewing.files.id'] [parameters: {'storage_file_id': None, 'filename': 'senekane_et_al_dp_student_t_mechanism.pdf', 'contribution_id': 109, 'storage_backend': None, 'content_type': 'application/pdf', 'revision_id': 1, 'md5': u'', 'size': 0}]

**Comment by ThiefMaster** [comment]
Copying the traceback from the other issue so we have it in one place:

```
Traceback (most recent call last): |/opt/indico/.venv/bin/indico-migrate:11
[<module>]
 |/opt/indico/.venv/local/lib/python2.7/site-packages/indico_migrate/cli.py:126
[main]
 |/opt/indico/.venv/local/lib/python2.7/site-packages/click/core.py:722
[__call__]
 |/opt/indico/.venv/local/lib/python2.7/site-packages/click/core.py:697
[main]
 |/opt/indico/.venv/local/lib/python2.7/site-packages/click/core.py:895
[invoke]
 |/opt/indico/.venv/local/lib/python2.7/site-packages/click/core.py:535
[invoke]
 |/opt/indico/.venv/local/lib/python2.7/site-packages/indico_migrate/cli.py:122
[cli]
 debug=debug, **kwargs)
 |/opt/indico/.venv/local/lib/python2.7/site-packages/indico_migrate/migrate.py:106
[migrate]
 |/opt/indico/.venv/local/lib/python2.7/site-packages/indico_migrate/importer.py:161
[run]
 |/opt/indico/.venv/local/lib/python2.7/site-packages/indico_migrate/util.py:323
[_f]
 |/opt/indico/.venv/local/lib/python2.7/site-packages/indico_migrate/steps/events/importer.py:183
[migrate]
 |/opt/indico/.venv/local/lib/python2.7/site-packages/indico_migrate/steps/events/importer.py:211
[migrate_event_data]
 |/opt/indico/.venv/local/lib/python2.7/site-packages/indico_migrate/steps/events/importer.py:137
[run_step]
 |/opt/indico/.venv/local/lib/python2.7/site-packages/indico_migrate/steps/events/__init__.py:83
[run]
 |/opt/indico/.venv/local/lib/python2.7/site-packages/indico_migrate/steps/events/papers.py:116
[migrate]
 |/opt/indico/.venv/local/lib/python2.7/site-packages/indico_migrate/steps/events/papers.py:344
[_migrate_papers]
 |/opt/indico/.venv/local/lib/python2.7/site-packages/indico_migrate/steps/events/papers.py:326
[_migrate_revisions]
...
 |/opt/indico/.venv/local/lib/python2.7/site-packages/sqlalchemy/engine/default.py:470
[do_execute]
 cursor.execute(statement, parameters)

(psycopg2.IntegrityError) null value in column "storage_backend" violates
not-null constraint
DETAIL:  Failing row contains (11, 688, 7, 0, null, application/pdf, ,
null, 341_D1_Middleton.pdf).
 [SQL: 'INSERT INTO event_paper_reviewing.files (contribution_id,
revision_id, size, storage_backend, content_type, md5, storage_file_id,
filename) VALUES (%(contribution_id)s, %(revision_id)s, %(size)s,
%(storage_backend)s, %(content_type)s, %(md5)s, %(storage_file_id)s,
%(filename)s) RETURNING event_paper_reviewing.files.id'] [parameters:
{'storage_file_id': None, 'filename': '341_D1_Middleton.pdf',
'contribution_id': 688, 'storage_backend': None, 'content_type':
'application/pdf', 'revision_id': 7, 'size': 0, 'md5': u''}]
```

**Comment by mokhinetc** [comment]
```
Traceback (most recent call last): |/opt/indico/.venv/bin/indico-migrate:11 [<module>]
 |/opt/indico/.venv/local/lib/python2.7/site-packages/indico_migrate/cli.py:126 [main]
 |/opt/indico/.venv/local/lib/python2.7/site-packages/click/core.py:722 [__call__]
 |/opt/indico/.venv/local/lib/python2.7/site-packages/click/core.py:697 [main]
 |/opt/indico/.venv/local/lib/python2.7/site-packages/click/core.py:895 [invoke]
 |/opt/indico/.venv/local/lib/python2.7/site-packages/click/core.py:535 [invoke]
 |/opt/indico/.venv/local/lib/python2.7/site-packages/indico_migrate/cli.py:122 [cli]
 debug=debug, **kwargs)
 |/opt/indico/.venv/local/lib/python2.7/site-packages/indico_migrate/migrate.py:106 [migrate]
 |/opt/indico/.venv/local/lib/python2.7/site-packages/indico_migrate/importer.py:161 [run]
 |/opt/indico/.venv/local/lib/python2.7/site-packages/indico_migrate/util.py:323 [_f]
 |/opt/indico/.venv/local/lib/python2.7/site-packages/indico_migrate/steps/events/importer.py:183 [migrate]
 |/opt/indico/.venv/local/lib/python2.7/site-packages/indico_migrate/steps/events/importer.py:211 [migrate_event_data]
 |/opt/indico/.venv/local/lib/python2.7/site-packages/indico_migrate/steps/events/importer.py:137 [run_step]
 |/opt/indico/.venv/local/lib/python2.7/site-packages/indico_migrate/steps/events/__init__.py:83 [run]
 |/opt/indico/.venv/local/lib/python2.7/site-packages/indico_migrate/steps/events/papers.py:116 [migrate]
 |/opt/indico/.venv/local/lib/python2.7/site-packages/indico_migrate/steps/events/papers.py:344 [_migrate_papers]
 |/opt/indico/.venv/local/lib/python2.7/site-packages/indico_migrate/steps/events/papers.py:326 [_migrate_revisions]
...
 |/opt/indico/.venv/local/lib/python2.7/site-packages/sqlalchemy/engine/default.py:470 [do_execute]
 cursor.execute(statement, parameters)

(psycopg2.IntegrityError) null value in column "storage_backend" violates not-null constraint
DETAIL:  Failing row contains (1, 109, 1, 0, null, application/pdf, , null, senekane_et_al_dp_student_t_mechanism.pdf).
 [SQL: 'INSERT INTO event_paper_reviewing.files (contribution_id, revision_id, size, storage_backend, content_type, md5, storage_file_id, filename) VALUES (%(contribution_id)s, %(revision_id)s, %(size)s, %(storage_backend)s, %(content_type)s, %(md5)s, %(storage_file_id)s, %(filename)s) RETURNING event_paper_reviewing.files.id'] [parameters: {'storage_file_id': None, 'filename': 'senekane_et_al_dp_student_t_mechanism.pdf', 'contribution_id': 109, 'storage_backend': None, 'content_type': 'application/pdf', 'revision_id': 1, 'md5': u'', 'size': 0}]
```

**Comment by ThiefMaster** [comment]
please try applying this patch:

```diff
diff --git a/indico_migrate/steps/events/papers.py b/indico_migrate/steps/events/papers.py
index 7179766..92a9eb8 100644
--- a/indico_migrate/steps/events/papers.py
+++ b/indico_migrate/steps/events/papers.py
@@ -383,6 +383,10 @@ class EventPaperReviewingImporter(LocalFileImporterMixin, EventMigrationStep):
         storage_backend, storage_path, size, md5 = self._get_local_file_info(resource)
         content_type = mimetypes.guess_type(resource.fileName)[0] or 'application/octet-stream'

+        if not storage_path:
+            self.print_error("%[red!]File not accessible [{}]".format(convert_to_unicode(resource.fileName)))
+            return
+
         paper_file = PaperFile(filename=resource.fileName, content_type=content_type,
                                size=size, md5=md5, storage_backend=storage_backend,
                                storage_file_id=storage_path, created_dt=created_dt)
```

**Comment by mokhinetc** [comment]
Hi @ThiefMaster , I've tried the patch and now i am getting the following error:

```
Traceback (most recent call last): |/opt/indico/.venv/bin/indico-migrate:11 [<module>]
 |/opt/indico/.venv/local/lib/python2.7/site-packages/indico_migrate/cli.py:126 [main]
 |/opt/indico/.venv/local/lib/python2.7/site-packages/click/core.py:722 [__call__]
 |/opt/indico/.venv/local/lib/python2.7/site-packages/click/core.py:697 [main]
 |/opt/indico/.venv/local/lib/python2.7/site-packages/click/core.py:895 [invoke]
 |/opt/indico/.venv/local/lib/python2.7/site-packages/click/core.py:535 [invoke]
 |/opt/indico/.venv/local/lib/python2.7/site-packages/indico_migrate/cli.py:122 [cli]
 debug=debug, **kwargs)
 |/opt/indico/.venv/local/lib/python2.7/site-packages/indico_migrate/migrate.py:106 [migrate]
 |/opt/indico/.venv/local/lib/python2.7/site-packages/indico_migrate/importer.py:161 [run]
 |/opt/indico/.venv/local/lib/python2.7/site-packages/indico_migrate/util.py:323 [_f]
 |/opt/indico/.venv/local/lib/python2.7/site-packages/indico_migrate/steps/events/importer.py:183 [migrate]
 |/opt/indico/.venv/local/lib/python2.7/site-packages/indico_migrate/steps/events/importer.py:194 [migrate_event_data]
 |/opt/indico/.venv/local/lib/python2.7/site-packages/indico_migrate/steps/events/importer.py:49 [_get_all_steps]
 from indico_migrate.steps.events.papers import EventPaperReviewingImporter

unindent does not match any outer indentation level (papers.py, line 95)
```

**Comment by ThiefMaster** [comment]
How did you apply the patch? This sounds a lot like the indentation is wrong, e.g. by adding it manually and using tabs instead of spaces to indent.

**Comment by mokhinetc** [comment]
Sorry about that, not much of a python programmer. below is how i inserted the code:

![image](https://user-images.githubusercontent.com/33443800/42993331-6693947c-8c0b-11e8-827d-648fd3f9f941.png)

**Comment by ThiefMaster** [comment]
You need to insert it at the correct place. Please undo your change and add the snippet

```python
        if not storage_path:
            self.print_error("%[red!]File not accessible [{}]".format(convert_to_unicode(resource.fileName)))
            return
```

below this line:

    content_type = mimetypes.guess_type(resource.fileName)[0] or 'application/octet-stream'

**Comment by mokhinetc** [comment]
I don't know what I am doing wrong, can you please attach the updated file and will upload and run it on the server.

**Comment by mokhinetc** [comment]
I am getting the following error:

Traceback (most recent call last): |/opt/indico/.venv/bin/indico-migrate:11 [<module>]
 |/opt/indico/.venv/local/lib/python2.7/site-packages/indico_migrate/cli.py:126 [main]
 |/opt/indico/.venv/local/lib/python2.7/site-packages/click/core.py:722 [__call__]
 |/opt/indico/.venv/local/lib/python2.7/site-packages/click/core.py:697 [main]
 |/opt/indico/.venv/local/lib/python2.7/site-packages/click/core.py:895 [invoke]
 |/opt/indico/.venv/local/lib/python2.7/site-packages/click/core.py:535 [invoke]
 |/opt/indico/.venv/local/lib/python2.7/site-packages/indico_migrate/cli.py:122 [cli]
 debug=debug, **kwargs)
 |/opt/indico/.venv/local/lib/python2.7/site-packages/indico_migrate/migrate.py:106 [migrate]
 |/opt/indico/.venv/local/lib/python2.7/site-packages/indico_migrate/importer.py:161 [run]
 |/opt/indico/.venv/local/lib/python2.7/site-packages/indico_migrate/util.py:323 [_f]
 |/opt/indico/.venv/local/lib/python2.7/site-packages/indico_migrate/steps/events/importer.py:183 [migrate]
 |/opt/indico/.venv/local/lib/python2.7/site-packages/indico_migrate/steps/events/importer.py:194 [migrate_event_data]
 |/opt/indico/.venv/local/lib/python2.7/site-packages/indico_migrate/steps/events/importer.py:49 [_get_all_steps]
 from indico_migrate.steps.events.papers import EventPaperReviewingImporter

'return' outside function (papers.py, line 97)

**Comment by ThiefMaster** [comment]
My last comment specified exactly where you had to put the code...
Anyway, here's the modified file: https://bpaste.net/raw/ef2e8eedf772
